import type { Metadata } from "next";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { Roboto_Mono } from "next/font/google";
import localFont from "next/font/local";
import { SolanaProvider } from "@/components/solana-provider";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

const rebels = localFont({
  src: "../../public/fonts/Rebels-Fett.woff2",
  variable: "--font-rebels",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Shinrai node",
  description: "Generated by Shinrai team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`font-mono antialiased ${robotoMono.variable} ${rebels.variable}`}
      >
        <SolanaProvider>
          <TRPCReactProvider>
            {children}
            <Toaster/>
          </TRPCReactProvider>
        </SolanaProvider>
      </body>
    </html>
  );
}
